export * from './Button/Button';
export * from './CardInscripciones/CardInscripciones';
export * from './CardNivelLectivo/CardNivelLectivo';
export * from './Contacto/Contacto';
export * from './Deporte/Deporte';
export { default as Footer } from './Footer/Footer';
export * from './Hero/Hero';
export * from './Navbar/Navbar';
export * from './NivelesLectivo/NivelesLectivo';
export * from './Novedades/Novedades';
export { default as CardSection } from './Sections/CardSection/CardSection';
export { default as Sections } from './Sections/Sections';
export * from './Testimonios/Testimonios';
export * from './TestimoniosCard/TestimoniosCard';
