export * from './Button/Button';
export * from './CardInscripciones/CardInscripciones';
export * from './CardNivelLectivo/CardNivelLectivo';
export * from '../pages/CargarCV/CargarCV';
export * from './CartelHero/CartelHero';
export * from './Deporte/Deporte';
export * from './DeporteNovedades/DeporteNovedades';
export { default as Footer } from './Footer/Footer';
export * from './FormContacto/FormContacto';
export * from './Hero/Hero';
export * from './HeroContacto/HeroContacto';
export * from './HeroNovedades/HeroNovedades';
export * from './Navbar/Navbar';
export * from './NivelesLectivo/NivelesLectivo';
export { default as CardSection } from './Sections/CardSection/CardSection';
export * from './Sections/CardSection/SectionDetalle';
export { default as Sections } from './Sections/Sections';
export * from './TarjetaNodos/TarjetaNodos';
export * from './TarjetaProyectoESI/TarjetaProyectoESI';
export * from './Testimonios/Testimonios';
export * from './TestimoniosCard/TestimoniosCard';
